//! Behavior-replay conformance against the TLA+ model (model-based testing).
//!
//! `spec/tla/behaviors/Conservation.json` is the COMPLETE transition coverage
//! of `Conservation.tla` at its configured bounds (MaxUnits=3,
//! MaxOperations=6 → 207 states / 678 transitions), generated by
//! `scripts/tla-behaviors.py` from TLC's state-graph dump. Every behavior is
//! replayed here against the real [`Inventory`], asserting after each step
//! that the abstraction of the implementation state equals the spec state:
//!
//! - `inventory`  == `inv.units("AAPL")`
//! - `totalAdded` / `totalReduced` == harness accumulators
//!
//! plus the enabledness obligation: an action the model says is ENABLED must
//! succeed in the implementation (a spec-legal `Reduce` may not `Err`).
//!
//! This is exhaustive conformance *up to the model bound* — strictly stronger
//! than the sampled properties in `tla_proptest.rs`, one notch below a full
//! refinement proof. The corpus is committed so this test is hermetic (no
//! Java/TLC); the TLA+ CI workflow regenerates it from the spec and fails on
//! drift, keeping model and corpus in lockstep.

use rust_decimal::Decimal;
use rustledger_core::{Amount, BookingMethod, Cost, Inventory, Position};

const CURRENCY: &str = "AAPL";

fn corpus_path() -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../spec/tla/behaviors/Conservation.json")
}

#[test]
fn replay_every_conservation_behavior() {
    // Graceful skip when spec/ isn't packaged (published-crate builds strip
    // it, and the Nix flake's source filter does too — the #1659 lesson).
    let Ok(raw) = std::fs::read_to_string(corpus_path()) else {
        eprintln!(
            "skipping replay_every_conservation_behavior: {} not present (published-crate build)",
            corpus_path().display()
        );
        return;
    };
    let corpus: serde_json::Value = serde_json::from_str(&raw).expect("corpus is valid JSON");

    let behaviors = corpus["behaviors"].as_array().expect("behaviors array");
    let transitions = corpus["coverage"]["transitions"]
        .as_u64()
        .expect("coverage.transitions");
    // Guard against a truncated corpus silently weakening the guarantee: the
    // behavior set must cover every transition TLC enumerated.
    assert!(
        behaviors.len() as u64 >= transitions * 9 / 10 && !behaviors.is_empty(),
        "corpus covers {} behaviors for {} transitions — regenerate with \
         scripts/tla-behaviors.py",
        behaviors.len(),
        transitions
    );

    let cost = Cost::new(Decimal::ONE, "USD")
        .with_date(rustledger_core::naive_date(2024, 1, 1).expect("valid date"));

    for (bi, behavior) in behaviors.iter().enumerate() {
        let mut inv = Inventory::new();
        let mut total_added = Decimal::ZERO;
        let mut total_reduced = Decimal::ZERO;

        for (si, step) in behavior
            .as_array()
            .expect("behavior array")
            .iter()
            .enumerate()
        {
            let step = step.as_array().expect("step array");
            let action = step[0].as_str().expect("action");
            let units = Decimal::from(step[1].as_i64().expect("units"));
            let spec_inventory = Decimal::from(step[2].as_i64().expect("inventory"));
            let spec_added = Decimal::from(step[3].as_i64().expect("totalAdded"));
            let spec_reduced = Decimal::from(step[4].as_i64().expect("totalReduced"));

            match action {
                "Add" => {
                    inv.add(Position::with_cost(
                        Amount::new(units, CURRENCY),
                        cost.clone(),
                    ));
                    total_added += units;
                }
                "Reduce" => {
                    // Enabledness obligation: the model only emits this
                    // transition when the guard held, so the implementation
                    // must be able to take it.
                    let result = inv
                        .reduce(&Amount::new(-units, CURRENCY), None, BookingMethod::Fifo)
                        .unwrap_or_else(|e| {
                            panic!(
                                "behavior {bi} step {si}: model-enabled Reduce({units}) \
                                 failed in the implementation: {e}"
                            )
                        });
                    let matched: Decimal =
                        result.matched.iter().map(|p| p.units.number.abs()).sum();
                    assert_eq!(
                        matched, units,
                        "behavior {bi} step {si}: Reduce matched {matched}, spec reduced {units}"
                    );
                    total_reduced += units;
                }
                other => panic!("behavior {bi} step {si}: unknown action {other:?}"),
            }

            // Abstraction check: implementation state == spec state, after
            // EVERY step of EVERY behavior.
            assert_eq!(
                inv.units(CURRENCY),
                spec_inventory,
                "behavior {bi} step {si} ({action} {units}): inventory diverged from the model"
            );
            assert_eq!(
                total_added, spec_added,
                "behavior {bi} step {si}: totalAdded diverged from the model"
            );
            assert_eq!(
                total_reduced, spec_reduced,
                "behavior {bi} step {si}: totalReduced diverged from the model"
            );
        }
    }

    println!(
        "replayed {} behaviors covering {} model transitions",
        behaviors.len(),
        transitions
    );
}
