// AUTO-GENERATED -- DO NOT EDIT.
//
// This file is regenerated by `scripts/regen-ts-bindings.sh` from the
// Rust DTOs in `crates/rustledger-wasm/src/types.rs`. Run the script
// after changing any DTO; CI fails if this file drifts from the
// generator output. See ADR-0004 (#1218) for the design.


/**
 * Amount value for serialization.
 */
export type AmountValue = { 
/**
 * The number as a string.
 */
number: string, 
/**
 * The currency.
 */
currency: string, };


/**
 * Wire-format of the numeric component of a [`PostingCostJson`].
 *
 * Mirrors `rustledger_core::CostNumber` on the wire so JS consumers
 * see the same mutual exclusion the host enforces. Use the `kind`
 * field as the discriminator.
 */
export type CostNumberJson = { "kind": "per_unit", 
/**
 * Per-unit value.
 */
value: string, } | { "kind": "total", 
/**
 * Total value.
 */
value: string, } | { "kind": "per_unit_from_total", 
/**
 * Derived per-unit.
 */
per_unit: string, 
/**
 * Source total.
 */
total: string, };


/**
 * A directive in JSON-serializable form.
 *
 * Each variant corresponds to a Beancount directive type, with fields
 * representing the directive's data in a JavaScript-friendly format.
 *
 * All variants carry a `meta` field with user-defined key/value
 * metadata from the source (issue #1168). Empty metadata serializes
 * as an absent field, so existing consumers continue to see the
 * pre-#1168 shape on directives without explicit metadata.
 */
export type DirectiveJson = { "type": "transaction", date: string, flag: string, 
/**
 * Optional payee. Mirrors FFI-WASI's shape: absent on the
 * wire when `None` (closes #1221).
 */
payee?: string, 
/**
 * Optional narration. Empty narrations are normalized to
 * `None` in `convert.rs` so the field is absent on the wire
 * in the empty case -- matches FFI-WASI's pattern (#1221).
 */
narration?: string, tags: Array<string>, links: Array<string>, postings: Array<PostingJson>, meta?: { [key in string]: MetaValueJson }, } | { "type": "balance", date: string, account: string, amount: AmountValue, 
/**
 * Explicit tolerance from the `~ 0.01` annotation, stringified.
 * Mirrors `rustledger_core::Balance::tolerance`.
 */
tolerance?: string, meta?: { [key in string]: MetaValueJson }, } | { "type": "open", date: string, account: string, currencies: Array<string>, booking?: string, meta?: { [key in string]: MetaValueJson }, } | { "type": "close", date: string, account: string, meta?: { [key in string]: MetaValueJson }, } | { "type": "commodity", date: string, currency: string, meta?: { [key in string]: MetaValueJson }, } | { "type": "pad", date: string, account: string, source_account: string, meta?: { [key in string]: MetaValueJson }, } | { "type": "event", date: string, event_type: string, value: string, meta?: { [key in string]: MetaValueJson }, } | { "type": "note", date: string, account: string, comment: string, meta?: { [key in string]: MetaValueJson }, } | { "type": "document", date: string, account: string, path: string, 
/**
 * Tags attached to the document directive (issue #1144).
 */
tags?: Array<string>, 
/**
 * Links attached to the document directive (issue #1144).
 */
links?: Array<string>, meta?: { [key in string]: MetaValueJson }, } | { "type": "price", date: string, currency: string, amount: AmountValue, meta?: { [key in string]: MetaValueJson }, } | { "type": "query", date: string, name: string, query_string: string, meta?: { [key in string]: MetaValueJson }, } | { "type": "custom", date: string, custom_type: string, 
/**
 * Positional values after the `custom TYPE` keyword. Each
 * entry is a [`TypedValueJson`] (`{type, value}`) — the
 * tagged shape preserves the host `MetaValue` variant tag so
 * JS consumers can distinguish a `Date` from a `String` from
 * an `Account` (closes #1207). Mirrors FFI-WASI's
 * `Vec<TypedValue>` exactly.
 */
values?: Array<TypedValueJson>, meta?: { [key in string]: MetaValueJson }, };


/**
 * Metadata-value wire format for WASM consumers.
 *
 * **JSON output is byte-equivalent to FFI-WASI's
 * `meta_value_to_json`** — JS clients writing portable code see
 * identical metadata values from both bindings. The Rust-side
 * types are independent though: FFI-WASI emits
 * `serde_json::Value` (untyped), this crate emits a typed enum.
 * Unifying the source-of-truth is tracked by issue #1200 item 2.
 *
 * The host's [`rustledger_core::MetaValue`] is richer than the wire
 * type — `Account`/`Currency`/`Tag`/`Link`/`Date`/`Number` all
 * flatten to JSON strings here, matching FFI-WASI behavior. JS
 * consumers that need the strong type info should query the host
 * via a typed API; this enum is the lossy-but-portable view.
 *
 * Untagged on the wire: `"hello"` serializes as a string,
 * `true` as a boolean, `null` as null, and an [`AmountValue`]
 * `{number,currency}` as a plain object. The TypeScript union is
 * `Record<string, string | boolean | {number, currency} | null>` —
 * no raw JSON number arm because `MetaValue::Number` (`Decimal`)
 * stringifies to preserve precision. Issue #1168 proposed
 * `string | number | boolean | null`; we substitute the
 * `{number,currency}` shape for `number` so cost-bearing metadata
 * round-trips cleanly and so JS numeric literals don't silently
 * alias into the wire (see the `meta_value_json_rejects_raw_json_number`
 * test).
 */
export type MetaValueJson = string | boolean | { 
/**
 * The decimal quantity, stringified for precision.
 */
number: string, 
/**
 * The currency code.
 */
currency: string, } | null;


/**
 * A posting cost in JSON-serializable form.
 */
export type PostingCostJson = { 
/**
 * Cost number (per-unit, total, or post-booking pair).
 */
number?: CostNumberJson, 
/**
 * Cost currency.
 */
currency?: string, 
/**
 * Acquisition date.
 */
date?: string, 
/**
 * Lot label.
 */
label?: string, };


/**
 * A posting in JSON-serializable form.
 */
export type PostingJson = { 
/**
 * Account name.
 */
account: string, 
/**
 * Units (amount).
 */
units?: AmountValue, 
/**
 * Cost specification.
 */
cost?: PostingCostJson, 
/**
 * Price annotation.
 */
price?: AmountValue, 
/**
 * Posting-level flag (e.g., `"!"` for pending). Mirrors
 * `rustledger_core::Posting::flag`.
 */
flag?: string, 
/**
 * Posting-level metadata (issue #1168). Empty when the posting
 * has no explicit metadata.
 */
meta?: { [key in string]: MetaValueJson }, };


/**
 * Tagged-union value used in `DirectiveJson::Custom`'s `values` field
 * (issue #1207). Narrowed discriminated union -- `switch (v.type)` (or
 * `if (v.type === "amount")`) narrows `v.value` to the right payload
 * shape.
 *
 * **Hand-tuned override** of the auto-generated `TypedValueJson` -- the
 * Rust DTO is a struct, not a tagged enum, so ts-rs can't emit the
 * narrowing on its own. See ADR-0004 (#1218).
 */
export type TypedValueJson =
    | { type: "string"; value: string }
    | { type: "account"; value: string }
    | { type: "currency"; value: string }
    | { type: "tag"; value: string }
    | { type: "link"; value: string }
    | { type: "date"; value: string }
    | { type: "number"; value: string }
    | { type: "bool"; value: boolean }
    | { type: "amount"; value: { number: string; currency: string } }
    | { type: "null"; value: null };
