# AUTO-GENERATED -- DO NOT EDIT.
#
# This file is regenerated by `scripts/regen-bindings.sh` from the
# JSON Schema at `crates/rustledger-wasm/bindings/index.schema.json`,
# which in turn comes from the Rust DTOs in
# `crates/rustledger-wasm/src/types.rs`. CI fails if this file drifts.
# See ADR-0004 (#1218 + #1232 for Phase 3) for the design.

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field, RootModel


class AmountValue(BaseModel):
    """
    Amount value for serialization.
    """

    currency: str = Field(..., description="The currency.")
    number: str = Field(..., description="The number as a string.")


class CostNumberJson1(BaseModel):
    """
    Per-unit cost (e.g., `{100 USD}`).
    """

    kind: Literal["per_unit"]
    value: str = Field(..., description="Per-unit value.")


class CostNumberJson2(BaseModel):
    """
    Total cost as written (e.g., `{{1000 USD}}`), pre-booking.
    """

    kind: Literal["total"]
    value: str = Field(..., description="Total value.")


class CostNumberJson3(BaseModel):
    """
    Post-booking derived per-unit with preserved source total.
    """

    kind: Literal["per_unit_from_total"]
    per_unit: str = Field(..., description="Derived per-unit.")
    total: str = Field(..., description="Source total.")


class CostNumberJson(RootModel[CostNumberJson1 | CostNumberJson2 | CostNumberJson3]):
    root: CostNumberJson1 | CostNumberJson2 | CostNumberJson3 = Field(
        ...,
        description="Wire-format of the numeric component of a [`PostingCostJson`].\n\nMirrors `rustledger_core::CostNumber` on the wire so JS consumers\nsee the same mutual exclusion the host enforces. Use the `kind`\nfield as the discriminator.",
    )


class LedgerOptions(BaseModel):
    """
    Ledger options.
    """

    operating_currencies: list[str] = Field(..., description="Operating currencies.")
    title: str | None = Field(
        None,
        description="Ledger title. Emitted as JSON `null` when no title is set\n(no `skip_serializing_if`; field is always present on the\nwire). TS: `string | null`, not `title?`.",
    )


class MetaValueJson1(BaseModel):
    """
    Amount values (`{number, currency}`) — the only structured
    shape that survives the round-trip. Same `{number, currency}`
    envelope as [`AmountValue`] so JS consumers can branch on
    shape without a discriminator tag.

    **Deserialize note**: serde's untagged-enum matcher accepts
    extra fields in a JSON object (`#[serde(deny_unknown_fields)]`
    can't be applied per-variant on an untagged enum without
    breaking the wider match). A JS client sending
    `{number: "100", currency: "USD", extra: "x"}` deserializes as
    `Amount { number: "100", currency: "USD" }` with `extra`
    silently dropped. Output-side consumers (the production path)
    are unaffected; treat `Deserialize` here as best-effort and
    validate at the host boundary if you need stricter checks.
    """

    currency: str = Field(..., description="The currency code.")
    number: str = Field(
        ..., description="The decimal quantity, stringified for precision."
    )


class MetaValueJson(RootModel[str | bool | MetaValueJson1 | None]):
    root: str | bool | MetaValueJson1 | None = Field(
        ...,
        description="Metadata-value wire format for WASM consumers.\n\n**JSON output is byte-equivalent to FFI-WASI's\n`meta_value_to_json`** — JS clients writing portable code see\nidentical metadata values from both bindings. The Rust-side\ntypes are independent though: FFI-WASI emits\n`serde_json::Value` (untyped), this crate emits a typed enum.\nUnifying the source-of-truth is tracked by issue #1200 item 2.\n\nThe host's [`rustledger_core::MetaValue`] is richer than the wire\ntype — `Account`/`Currency`/`Tag`/`Link`/`Date`/`Number` all\nflatten to JSON strings here, matching FFI-WASI behavior. JS\nconsumers that need the strong type info should query the host\nvia a typed API; this enum is the lossy-but-portable view.\n\nUntagged on the wire: `\"hello\"` serializes as a string,\n`true` as a boolean, `null` as null, and an [`AmountValue`]\n`{number,currency}` as a plain object. The TypeScript union is\n`Record<string, string | boolean | {number, currency} | null>` —\nno raw JSON number arm because `MetaValue::Number` (`Decimal`)\nstringifies to preserve precision. Issue #1168 proposed\n`string | number | boolean | null`; we substitute the\n`{number,currency}` shape for `number` so cost-bearing metadata\nround-trips cleanly and so JS numeric literals don't silently\nalias into the wire (see the `meta_value_json_rejects_raw_json_number`\ntest).",
    )


class PostingCostJson(BaseModel):
    """
    A posting cost in JSON-serializable form.
    """

    currency: str | None = Field(None, description="Cost currency.")
    date: str | None = Field(None, description="Acquisition date.")
    label: str | None = Field(None, description="Lot label.")
    number: CostNumberJson | None = Field(
        None, description="Cost number (per-unit, total, or post-booking pair)."
    )


class PostingJson(BaseModel):
    """
    A posting in JSON-serializable form.
    """

    account: str = Field(..., description="Account name.")
    cost: PostingCostJson | None = Field(None, description="Cost specification.")
    flag: str | None = Field(
        None,
        description='Posting-level flag (e.g., `"!"` for pending). Mirrors\n`rustledger_core::Posting::flag`.',
    )
    meta: dict[str, MetaValueJson | None] | None = Field(
        None,
        description="Posting-level metadata (issue #1168). Empty when the posting\nhas no explicit metadata.",
    )
    price: AmountValue | None = Field(None, description="Price annotation.")
    units: AmountValue | None = Field(None, description="Units (amount).")


class Severity(RootModel[Literal["error", "warning"]]):
    root: Literal["error", "warning"] = Field(..., description="Error severity level.")


class TypedValueJson(BaseModel):
    """
    Tagged-union wire-format for a [`MetaValue`] that preserves the
    host's variant tag.

    Used **only** in `DirectiveJson::Custom`'s `values` field, where
    callers genuinely need to distinguish (for example) a `Date` from
    a `String` or an `Account` — all three of which collapse to a bare
    JSON string under the untagged [`MetaValueJson`] shape.

    Wire shape: `{"type": "<variant>", "value": ...}` — mirrors
    `rustledger-ffi-wasi::TypedValue` (see
    `crates/rustledger-ffi-wasi/src/types/output.rs::TypedValue`) so
    portable JS consumers see identical envelopes across both bindings.

    **Why `value: MetaValueJson` and not `serde_json::Value`** —
    `serde_json` is intentionally a host-only dev-dependency for this
    crate (the runtime build avoids it to keep the wasm32 dep chain
    small). [`MetaValueJson`] already covers every payload shape
    FFI-WASI's `TypedValue` emits: `String` for the string-flavored
    variants, `Bool` for `bool`, `Amount` for `amount`, `Null` for
    `null`. The serialized JSON is bit-identical to FFI-WASI's.

    `MetaValueJson` (untagged) is retained for the `meta` map of every
    directive — there the lossy shape is intentional and matches what
    FFI-WASI's metadata side also emits.

    **Breaking change from #1199** for the WASM binding: pre-#1207
    `Custom.values` emitted raw `MetaValueJson` values (lossy). Closes
    #1207.
    """

    type: str = Field(
        ...,
        description='Variant tag — one of `"string"`, `"account"`, `"currency"`,\n`"tag"`, `"link"`, `"date"`, `"number"`, `"bool"`, `"amount"`,\n`"null"`. Matches FFI-WASI\'s tag strings exactly.\n\nRenamed via `#[ts(type = ...)]` so the discriminator is a\nstring-literal union on the TS side. The post-process script\nfurther narrows the full struct shape into a discriminated\nunion (per-variant `{type, value}` rows) -- see ADR-0004 for\nwhy the narrowing is hand-tuned rather than generator-driven.',
    )
    value: MetaValueJson | None = Field(
        ..., description="Variant payload (see [`MetaValueJson`] for the four shapes)."
    )


class BeancountError(BaseModel):
    """
    An error with source location.

    **Renamed to `BeancountError` on the TS side** to avoid shadowing
    the JS-builtin `Error` type. The Rust struct keeps the shorter
    `Error` name for internal use; the rename is applied via
    `#[ts(rename = ...)]` so consumers see a non-shadowing name.
    """

    column: int | None = Field(
        None,
        description="Column number (1-based). `null` when the error has no source\nlocation.",
        ge=0,
    )
    line: int | None = Field(
        None,
        description="Line number (1-based). `null` when the error has no source\nlocation (e.g. validation errors not tied to a span).",
        ge=0,
    )
    message: str = Field(..., description="Error message.")
    severity: Severity = Field(..., description="Error severity.")


class DirectiveJson1(BaseModel):
    """
    Transaction directive.
    """

    date: str
    flag: str
    links: list[str]
    meta: dict[str, MetaValueJson | None] | None = None
    narration: str | None = Field(
        None,
        description="Optional narration. Empty narrations are normalized to\n`None` in `convert.rs` so the field is absent on the wire\nin the empty case -- matches FFI-WASI's pattern (#1221).",
    )
    payee: str | None = Field(
        None,
        description="Optional payee. Mirrors FFI-WASI's shape: absent on the\nwire when `None` (closes #1221).",
    )
    postings: list[PostingJson]
    tags: list[str]
    type: Literal["transaction"]


class DirectiveJson2(BaseModel):
    """
    Balance assertion.
    """

    account: str
    amount: AmountValue
    date: str
    meta: dict[str, MetaValueJson | None] | None = None
    tolerance: str | None = Field(
        None,
        description="Explicit tolerance from the `~ 0.01` annotation, stringified.\nMirrors `rustledger_core::Balance::tolerance`.",
    )
    type: Literal["balance"]


class DirectiveJson3(BaseModel):
    """
    Open account.
    """

    account: str
    booking: str | None = None
    currencies: list[str]
    date: str
    meta: dict[str, MetaValueJson | None] | None = None
    type: Literal["open"]


class DirectiveJson4(BaseModel):
    """
    Close account.
    """

    account: str
    date: str
    meta: dict[str, MetaValueJson | None] | None = None
    type: Literal["close"]


class DirectiveJson5(BaseModel):
    """
    Commodity declaration.
    """

    currency: str
    date: str
    meta: dict[str, MetaValueJson | None] | None = None
    type: Literal["commodity"]


class DirectiveJson6(BaseModel):
    """
    Pad directive.
    """

    account: str
    date: str
    meta: dict[str, MetaValueJson | None] | None = None
    source_account: str
    type: Literal["pad"]


class DirectiveJson7(BaseModel):
    """
    Event directive.
    """

    date: str
    event_type: str
    meta: dict[str, MetaValueJson | None] | None = None
    type: Literal["event"]
    value: str


class DirectiveJson8(BaseModel):
    """
    Note directive.
    """

    account: str
    comment: str
    date: str
    meta: dict[str, MetaValueJson | None] | None = None
    type: Literal["note"]


class DirectiveJson9(BaseModel):
    """
    Document directive.
    """

    account: str
    date: str
    links: list[str] | None = Field(
        None, description="Links attached to the document directive (issue #1144)."
    )
    meta: dict[str, MetaValueJson | None] | None = None
    path: str
    tags: list[str] | None = Field(
        None, description="Tags attached to the document directive (issue #1144)."
    )
    type: Literal["document"]


class DirectiveJson10(BaseModel):
    """
    Price directive.
    """

    amount: AmountValue
    currency: str
    date: str
    meta: dict[str, MetaValueJson | None] | None = None
    type: Literal["price"]


class DirectiveJson11(BaseModel):
    """
    Query directive.
    """

    date: str
    meta: dict[str, MetaValueJson | None] | None = None
    name: str
    query_string: str
    type: Literal["query"]


class DirectiveJson12(BaseModel):
    """
    Custom directive.

    `values` carries the positional arguments after the type
    keyword. Each value is a [`TypedValueJson`] tagged union
    (`{type, value}`) that preserves the host `MetaValue`
    variant tag, so JS consumers can distinguish (for example)
    a `Date` from a `String` from an `Account` — all of which
    would otherwise collapse to bare JSON strings under the
    untagged `MetaValueJson` shape.

    Pre-#1168: `values` was dropped entirely from the JSON output.
    Pre-#1207: present but emitted raw via `MetaValueJson` (lossy).
    Post-#1207: emitted via `TypedValueJson` (this variant), mirroring
    FFI-WASI's `Vec<TypedValue>`.

    Both `values` and `meta` use `skip_serializing_if` to omit
    the field when empty (consistent shape: a Custom directive
    with no positional args and no metadata serializes as
    `{type, date, custom_type}`, matching what the TS shape
    declares via `values?` / `meta?`).
    """

    custom_type: str
    date: str
    meta: dict[str, MetaValueJson | None] | None = None
    type: Literal["custom"]
    values: list[TypedValueJson] | None = Field(
        None,
        description="Positional values after the `custom TYPE` keyword. Each\nentry is a [`TypedValueJson`] (`{type, value}`) — the\ntagged shape preserves the host `MetaValue` variant tag so\nJS consumers can distinguish a `Date` from a `String` from\nan `Account` (closes #1207). Mirrors FFI-WASI's\n`Vec<TypedValue>` exactly.",
    )


class DirectiveJson(
    RootModel[
        DirectiveJson1
        | DirectiveJson2
        | DirectiveJson3
        | DirectiveJson4
        | DirectiveJson5
        | DirectiveJson6
        | DirectiveJson7
        | DirectiveJson8
        | DirectiveJson9
        | DirectiveJson10
        | DirectiveJson11
        | DirectiveJson12
    ]
):
    root: (
        DirectiveJson1
        | DirectiveJson2
        | DirectiveJson3
        | DirectiveJson4
        | DirectiveJson5
        | DirectiveJson6
        | DirectiveJson7
        | DirectiveJson8
        | DirectiveJson9
        | DirectiveJson10
        | DirectiveJson11
        | DirectiveJson12
    ) = Field(
        ...,
        description="A directive in JSON-serializable form.\n\nEach variant corresponds to a Beancount directive type, with fields\nrepresenting the directive's data in a JavaScript-friendly format.\n\nAll variants carry a `meta` field with user-defined key/value\nmetadata from the source (issue #1168). Empty metadata serializes\nas an absent field, so existing consumers continue to see the\npre-#1168 shape on directives without explicit metadata.",
    )


class LedgerJson(BaseModel):
    """
    A parsed Beancount ledger.

    **Renamed to `LedgerJson` on the TS side** to avoid colliding with
    the wasm-bindgen-exported `Ledger` class (the runtime wrapper that
    owns the parsed data). `LedgerJson` is the wire shape; `Ledger` is
    the class consumers instantiate via `Ledger.fromFiles(...)`. The
    Rust struct keeps the shorter name for internal use; the rename
    is applied via `#[ts(rename = ...)]`.
    """

    directives: list[DirectiveJson] = Field(
        ..., description="All directives in the ledger."
    )
    options: LedgerOptions = Field(..., description="Ledger options.")


class ParseResult(BaseModel):
    """
    Result of parsing a Beancount file.
    """

    errors: list[BeancountError] = Field(..., description="Parse errors.")
    ledger: LedgerJson | None = Field(
        None,
        description="The parsed ledger (if successful). Emitted as JSON `null` when\nparsing failed entirely; no `skip_serializing_if`, so the field\nis always present on the wire (TS: `Ledger | null`, not\n`ledger?`).",
    )
