//! `rledger format` ↔ `bean-format` compatibility tests (issue #1242).
//!
//! These pin the three correctness properties that close #1242:
//!
//! 1. **Golden output** — `rledger format` produces a specific canonical
//!    layout for a deliberately-misformatted file (the issue's repro).
//! 2. **Idempotence / fixed-point** — formatting an already-formatted file
//!    is a no-op (`format(format(x)) == format(x)`), so editors and CI stop
//!    churning.
//! 3. **bean-format parity** — Python `bean-format` leaves `rledger format`'s
//!    output byte-for-byte unchanged (and vice-versa for `-c`). This is the
//!    load-bearing property: a file formatted by either tool is a fixed point
//!    of the other, so mixing the two in a repo causes no diffs.
//!
//! The golden `.expected` fixtures were generated by `rledger format` and
//! verified to be bean-format (beancount 3.2.3) fixed points; property 3's
//! live test re-checks that whenever the podman compat image is available.

mod common;

use std::path::{Path, PathBuf};
use std::process::Command;

use common::project_root;

/// Run `rledger format <args> <file>` on `input`, returning stdout.
///
/// Writes `input` to a temp file because `rledger format` takes a path
/// argument (it does not read ledger text from stdin).
fn run_format(input: &str, extra_args: &[&str]) -> String {
    let Some(bin) = common::rledger_binary() else {
        // Callers must guard with `format_or_skip`; reaching here means the
        // binary vanished between the guard and now.
        unreachable!("run_format must be guarded by format_or_skip")
    };
    let dir = tempfile::tempdir().expect("create tempdir");
    let path = dir.path().join("ledger.beancount");
    std::fs::write(&path, input).expect("write temp ledger");

    let output = Command::new(bin)
        .arg("format")
        .args(extra_args)
        .arg(&path)
        .output()
        .expect("failed to run rledger format");

    assert!(
        output.status.success(),
        "rledger format failed: stderr={}",
        String::from_utf8_lossy(&output.stderr)
    );
    String::from_utf8(output.stdout).expect("format output is valid UTF-8")
}

/// Run `rledger format`, or return `None` (with an explicit skip message)
/// when the binary isn't built — mirrors the `require_rledger!` skip pattern
/// while still letting the caller `return` cleanly from `#[test]`.
fn format_or_skip(input: &str, extra_args: &[&str]) -> Option<String> {
    common::rledger_binary()?;
    Some(run_format(input, extra_args))
}

fn fixture(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/format")
        .join(name)
}

fn read_fixture(name: &str) -> String {
    std::fs::read_to_string(fixture(name)).unwrap_or_else(|e| panic!("read fixture {name}: {e}"))
}

#[test]
fn issue_1242_auto_golden() {
    let input = read_fixture("issue_1242_input.beancount");
    let expected = read_fixture("issue_1242_auto.expected");
    let Some(got) = format_or_skip(&input, &[]) else {
        return;
    };
    assert_eq!(
        got, expected,
        "auto-mode `rledger format` output drifted from the #1242 golden"
    );
}

#[test]
fn issue_1242_currency_column_60_golden() {
    let input = read_fixture("issue_1242_input.beancount");
    let expected = read_fixture("issue_1242_c60.expected");
    let Some(got) = format_or_skip(&input, &["-c", "60"]) else {
        return;
    };
    assert_eq!(
        got, expected,
        "`rledger format -c 60` output drifted from the #1242 golden"
    );
}

/// A small corpus of well-formed inputs. Formatting must be idempotent on
/// each: the second pass over already-formatted text changes nothing. This
/// also doubles as the fixed-point property — a canonical file is unchanged
/// by `rledger format`.
const CORPUS: &[&str] = &[
    // Standalone balance whose prefix is wider than the postings — the exact
    // shape that exposed #1242 (postings must align to the balance column).
    "; broken on purpose\n\n2024-01-01 open Assets:Bank:Checking USD\n2024-01-01 open Income:Salary\n\n2024-01-15 * \"Paycheck\"\n  Assets:Bank:Checking  5000 USD\n  Income:Salary  -5000 USD\n\n2024-01-16 balance Assets:Bank:Checking  5000 USD\n",
    // Cost specs and price annotations on postings.
    "2024-01-01 open Assets:Brokerage\n2024-01-01 open Assets:Cash\n\n2024-02-01 * \"Buy AAPL\"\n  Assets:Brokerage  10 AAPL {150.00 USD}\n  Assets:Cash  -1500.00 USD\n\n2024-03-01 price AAPL  185.50 USD\n",
    // Metadata + tags/links + a trailing comment on a posting.
    "2024-01-01 open Assets:Bank\n2024-01-01 open Expenses:Food\n\n2024-04-01 * \"Cafe\" #coffee ^trip-2024\n  receipt: \"r-1\"\n  Assets:Bank  -4.50 USD ; with tip\n  Expenses:Food\n",
    // Currency-only / amount-free postings interleaved with numbered ones.
    "2024-01-01 open Assets:A\n2024-01-01 open Assets:B\n\n2024-05-01 * \"mix\"\n  Assets:A  -10.00 USD\n  Assets:B\n",
];

#[test]
fn format_is_idempotent_on_corpus() {
    if common::rledger_binary().is_none() {
        eprintln!("Skipping: rledger binary not found");
        return;
    }
    for (i, input) in CORPUS.iter().enumerate() {
        let once = run_format(input, &[]);
        let twice = run_format(&once, &[]);
        assert_eq!(
            once, twice,
            "auto format not idempotent on corpus[{i}]:\n--- once ---\n{once}\n--- twice ---\n{twice}"
        );
    }
}

#[test]
fn format_currency_column_is_idempotent_on_corpus() {
    if common::rledger_binary().is_none() {
        eprintln!("Skipping: rledger binary not found");
        return;
    }
    for (i, input) in CORPUS.iter().enumerate() {
        let once = run_format(input, &["-c", "60"]);
        let twice = run_format(&once, &["-c", "60"]);
        assert_eq!(
            once, twice,
            "-c 60 format not idempotent on corpus[{i}]:\n--- once ---\n{once}\n--- twice ---\n{twice}"
        );
    }
}

// =============================================================================
// Live bean-format parity (requires the podman compat image)
// =============================================================================

/// Path to the `bean-format` podman wrapper.
fn bean_format_wrapper() -> PathBuf {
    project_root().join("scripts/bin/bean-format")
}

/// Whether the rustledger-compat podman image is available. When it isn't
/// (most CI, dev machines without podman), the parity tests skip explicitly
/// rather than fail — but an actual byte mismatch always fails loudly.
fn compat_image_available() -> bool {
    let tag = std::env::var("RUSTLEDGER_COMPAT_IMAGE")
        .unwrap_or_else(|_| "rustledger-compat:latest".to_string());
    Command::new("podman")
        .args(["image", "exists", &tag])
        .status()
        .is_ok_and(|s| s.success())
}

/// Run the `bean-format` wrapper on `path` with `extra_args`, returning stdout.
fn run_bean_format(path: &Path, extra_args: &[&str]) -> String {
    let output = Command::new(bean_format_wrapper())
        .args(extra_args)
        .arg(path)
        .output()
        .expect("failed to invoke bean-format wrapper");
    assert!(
        output.status.success(),
        "bean-format failed: stderr={}",
        String::from_utf8_lossy(&output.stderr)
    );
    String::from_utf8(output.stdout).expect("bean-format output is valid UTF-8")
}

/// `rledger format` output is a fixed point of `bean-format`: feeding our
/// canonical output back through Python's formatter changes nothing.
#[test]
fn rledger_auto_output_is_bean_format_fixed_point() {
    if common::rledger_binary().is_none() {
        eprintln!("Skipping: rledger binary not found");
        return;
    }
    if !compat_image_available() {
        eprintln!("Skipping: rustledger-compat podman image not available");
        return;
    }
    let dir = tempfile::tempdir().expect("create tempdir");
    for (i, input) in CORPUS.iter().enumerate() {
        let rledger_out = run_format(input, &[]);
        let path = dir.path().join(format!("c{i}.beancount"));
        std::fs::write(&path, &rledger_out).expect("write rledger output");
        let bean_out = run_bean_format(&path, &[]);
        assert_eq!(
            rledger_out, bean_out,
            "bean-format changed rledger's canonical output on corpus[{i}] — not a fixed point"
        );
    }
}

/// Cross-path identity: the `rledger format` CLI binary and a direct call
/// to the canonical `rustledger_parser::format_source` function produce
/// byte-identical output. This pins parity-by-construction across every
/// path that delegates to `format_source` — CLI, LSP, WASM, FFI — and
/// detects any regression where a caller starts re-implementing the
/// rendering pipeline locally.
#[test]
fn cli_matches_format_source_direct() {
    use rustledger_core::FormatConfig;
    use rustledger_parser::{format_source, parse};

    if common::rledger_binary().is_none() {
        eprintln!("Skipping: rledger binary not found");
        return;
    }
    let config = FormatConfig::default();
    for (i, input) in CORPUS.iter().enumerate() {
        let cli_out = run_format(input, &[]);
        let parse_result = parse(input);
        assert!(
            parse_result.errors.is_empty(),
            "corpus[{i}] must parse cleanly"
        );
        let direct = format_source(input, &parse_result, &config);
        assert_eq!(
            cli_out, direct,
            "CLI output diverged from direct format_source on corpus[{i}] — \
             the CLI must not re-implement the rendering pipeline"
        );
    }
}

/// Same parity property under `-c 60`: `rledger format -c 60` output is a
/// fixed point of `bean-format -c 60`.
#[test]
fn rledger_currency_column_output_is_bean_format_fixed_point() {
    if common::rledger_binary().is_none() {
        eprintln!("Skipping: rledger binary not found");
        return;
    }
    if !compat_image_available() {
        eprintln!("Skipping: rustledger-compat podman image not available");
        return;
    }
    let dir = tempfile::tempdir().expect("create tempdir");
    for (i, input) in CORPUS.iter().enumerate() {
        let rledger_out = run_format(input, &["-c", "60"]);
        let path = dir.path().join(format!("c{i}.beancount"));
        std::fs::write(&path, &rledger_out).expect("write rledger output");
        let bean_out = run_bean_format(&path, &["-c", "60"]);
        assert_eq!(
            rledger_out, bean_out,
            "bean-format -c 60 changed rledger's -c 60 output on corpus[{i}] — not a fixed point"
        );
    }
}
