//! Transaction booking with lot matching.
//!
//! This module handles:
//! - Tracking inventory across transactions
//! - Matching sold lots against existing holdings
//! - Calculating capital gains/losses
//! - Filling in cost specs for lot reductions

use rust_decimal::Decimal;
use rust_decimal_macros::dec;
use rustledger_core::{
    Amount, BookingMethod, Cost, CostSpec, IncompleteAmount, InternedStr, Inventory, Position,
    Posting, Transaction,
};
use std::collections::HashMap;
use thiserror::Error;

use crate::{InterpolationError, InterpolationResult, interpolate};

/// Quantize a calculated decimal value to reasonable precision.
/// This rounds to the minimum decimal places where error < 0.01.
fn quantize_calculated(d: Decimal) -> Decimal {
    let threshold = dec!(0.01);

    // If already clean (few decimal places), preserve it
    if d.scale() <= 2 {
        return d;
    }

    // Try progressively more decimal places until error is acceptable
    for precision in 2..=8 {
        let quantized = d.round_dp(precision);
        let error = (d - quantized).abs();
        if error < threshold {
            return quantized;
        }
    }

    // Fallback: round to 8 decimal places
    d.round_dp(8)
}

/// Errors that can occur during booking.
#[derive(Debug, Clone, Error)]
pub enum BookingError {
    /// No matching lot found for reduction.
    #[error("no matching lot for {units} in account {account}")]
    NoMatchingLot {
        /// The account being reduced.
        account: InternedStr,
        /// The units being reduced.
        units: String,
    },

    /// Insufficient units in matching lots.
    #[error("insufficient units: need {requested} but only {available} available")]
    InsufficientUnits {
        /// Requested reduction amount.
        requested: Decimal,
        /// Available amount.
        available: Decimal,
    },

    /// Interpolation failed after booking.
    #[error("interpolation failed: {0}")]
    Interpolation(#[from] InterpolationError),
}

/// Result of booking a single transaction.
#[derive(Debug, Clone)]
pub struct BookedTransaction {
    /// The transaction with costs filled in.
    pub transaction: Transaction,
    /// Capital gains/losses generated by this transaction.
    pub gains: Vec<CapitalGain>,
    /// Which posting indices had costs filled in.
    pub booked_indices: Vec<usize>,
}

/// A capital gain or loss from a lot sale.
#[derive(Debug, Clone)]
pub struct CapitalGain {
    /// The account holding the asset.
    pub account: InternedStr,
    /// The currency of the asset.
    pub currency: InternedStr,
    /// The gain amount (positive) or loss (negative).
    pub amount: Amount,
    /// Cost basis of the sold lot.
    pub cost_basis: Amount,
    /// Sale proceeds.
    pub proceeds: Amount,
}

/// Booking engine that tracks inventory across transactions.
#[derive(Debug, Default)]
pub struct BookingEngine {
    /// Inventory per account.
    inventories: HashMap<InternedStr, Inventory>,
    /// Default booking method.
    booking_method: BookingMethod,
}

impl BookingEngine {
    /// Create a new booking engine with default FIFO booking.
    #[must_use]
    pub fn new() -> Self {
        Self {
            inventories: HashMap::new(),
            booking_method: BookingMethod::Fifo,
        }
    }

    /// Create a booking engine with a specific booking method.
    #[must_use]
    pub fn with_method(method: BookingMethod) -> Self {
        Self {
            inventories: HashMap::new(),
            booking_method: method,
        }
    }

    /// Get the inventory for an account.
    #[must_use]
    pub fn inventory(&self, account: &InternedStr) -> Option<&Inventory> {
        self.inventories.get(account)
    }

    /// Book a transaction: fill in empty cost specs and calculate gains.
    ///
    /// This does NOT modify the internal inventories - call `apply` for that.
    ///
    /// When a reduction matches multiple lots (e.g., selling shares that were purchased
    /// across multiple buy transactions), the posting is expanded into multiple postings,
    /// one for each matched lot. This matches Python beancount's behavior.
    pub fn book(&self, txn: &Transaction) -> Result<BookedTransaction, BookingError> {
        let mut result = txn.clone();
        let mut gains = Vec::new();
        let mut booked_indices = std::collections::HashSet::new();
        // Track posting expansions: (original_idx, expanded_postings)
        let mut expansions: Vec<(usize, Vec<Posting>)> = Vec::new();

        // First pass: identify postings that need lot matching (reductions)
        for (idx, posting) in txn.postings.iter().enumerate() {
            // Check if this is a reduction with a cost spec
            if let Some(IncompleteAmount::Complete(units)) = &posting.units {
                if let Some(cost_spec) = &posting.cost {
                    // Check if this is a reduction (units have opposite sign of inventory)
                    // This handles both:
                    // - Selling long positions (negative units, positive inventory)
                    // - Closing short positions (positive units, negative inventory)
                    if let Some(inv) = self.inventories.get(&posting.account) {
                        // Check if inventory is_reduced_by these units
                        // (signs differ for the same currency)
                        let is_reduction = inv.positions().iter().any(|pos| {
                            pos.units.currency == units.currency
                                && pos.units.number.is_sign_positive()
                                    != units.number.is_sign_positive()
                        });

                        if is_reduction {
                            // Clone inventory to try booking
                            let mut inv_clone = inv.clone();
                            let reduction_amount = units.clone();

                            if let Ok(booking_result) = inv_clone.reduce(
                                &reduction_amount,
                                Some(cost_spec),
                                self.booking_method,
                            ) {
                                // Check if multiple lots were matched
                                if booking_result.matched.len() > 1 {
                                    // Expand single posting into multiple postings
                                    let mut expanded = Vec::new();
                                    for matched_pos in &booking_result.matched {
                                        let mut new_posting = posting.clone();
                                        // Set units to the matched portion with NEGATED sign
                                        // (matched_pos.units has the inventory sign, but we need
                                        // the reduction sign which is opposite)
                                        let expanded_units = rustledger_core::Amount::new(
                                            -matched_pos.units.number, // Negate: inventory→reduction
                                            matched_pos.units.currency.clone(),
                                        );
                                        new_posting.units =
                                            Some(IncompleteAmount::Complete(expanded_units));
                                        // Set cost from the matched lot
                                        if let Some(cost) = &matched_pos.cost {
                                            new_posting.cost = Some(CostSpec {
                                                number_per: Some(cost.number),
                                                number_total: None,
                                                currency: Some(cost.currency.clone()),
                                                date: cost.date,
                                                label: cost.label.clone(),
                                                merge: false,
                                            });
                                        }
                                        expanded.push(new_posting);
                                    }
                                    expansions.push((idx, expanded));
                                    booked_indices.insert(idx);
                                } else if let Some(cost_basis) = &booking_result.cost_basis {
                                    // Single lot match - update posting in place
                                    let per_unit = cost_basis.number / units.number.abs();
                                    // Use new_calculated since per_unit is computed from total/units
                                    let matched_cost =
                                        Cost::new_calculated(per_unit, cost_basis.currency.clone())
                                            .with_date_opt(
                                                booking_result
                                                    .matched
                                                    .first()
                                                    .and_then(|p| p.cost.as_ref())
                                                    .and_then(|c| c.date),
                                            );

                                    // Update posting with filled cost
                                    result.postings[idx].cost = Some(CostSpec {
                                        number_per: Some(matched_cost.number),
                                        number_total: None,
                                        currency: Some(matched_cost.currency.clone()),
                                        date: matched_cost.date,
                                        label: None,
                                        merge: false,
                                    });
                                    booked_indices.insert(idx);
                                }

                                // Calculate capital gain if there's a price
                                if let Some(cost_basis) = &booking_result.cost_basis {
                                    if let Some(price) = &posting.price {
                                        let sale_price = match price {
                                            rustledger_core::PriceAnnotation::Unit(a) => {
                                                a.number * units.number.abs()
                                            }
                                            rustledger_core::PriceAnnotation::Total(a) => a.number,
                                            _ => continue,
                                        };

                                        let gain_amount = sale_price - cost_basis.number;
                                        if !gain_amount.is_zero() {
                                            gains.push(CapitalGain {
                                                account: posting.account.clone(),
                                                currency: units.currency.clone(),
                                                amount: Amount::new(
                                                    gain_amount,
                                                    &cost_basis.currency,
                                                ),
                                                cost_basis: cost_basis.clone(),
                                                proceeds: Amount::new(
                                                    sale_price,
                                                    &cost_basis.currency,
                                                ),
                                            });
                                        }
                                    }
                                }
                            }
                        }
                        // If not a reduction: fall through to augmentation code below
                    }

                    if cost_spec.number_total.is_some() && cost_spec.number_per.is_none() {
                        // This is an augmentation with total cost - convert to per-unit
                        // e.g., `1.763 VIIIX {{300.00 USD}}` -> `1.763 VIIIX {170.16 USD}`
                        if let (Some(total), Some(currency)) =
                            (&cost_spec.number_total, &cost_spec.currency)
                        {
                            if !units.number.is_zero() {
                                // Calculate per-unit cost and quantize since it's computed
                                let per_unit_raw = *total / units.number.abs();
                                let per_unit = quantize_calculated(per_unit_raw);
                                result.postings[idx].cost = Some(CostSpec {
                                    number_per: Some(per_unit),
                                    number_total: None, // Clear total cost
                                    currency: Some(currency.clone()),
                                    // Fill in transaction date if no date specified
                                    date: cost_spec.date.or(Some(txn.date)),
                                    label: cost_spec.label.clone(),
                                    merge: cost_spec.merge,
                                });
                                booked_indices.insert(idx);
                            }
                        }
                    }

                    // Fill in dates and currencies for augmentations (not already booked)
                    if !booked_indices.contains(&idx)
                        && (cost_spec.number_per.is_some() || cost_spec.number_total.is_some())
                    {
                        // Cost spec has a number but may be missing date or currency
                        // Fill in missing parts from price annotation and transaction date
                        let inferred_currency = cost_spec.currency.clone().or_else(|| {
                            posting.price.as_ref().and_then(|p| match p {
                                rustledger_core::PriceAnnotation::Unit(a)
                                | rustledger_core::PriceAnnotation::Total(a) => {
                                    Some(a.currency.clone())
                                }
                                rustledger_core::PriceAnnotation::UnitIncomplete(inc)
                                | rustledger_core::PriceAnnotation::TotalIncomplete(inc) => {
                                    inc.currency().map(Into::into)
                                }
                                _ => None,
                            })
                        });

                        // Check if this is a reduction (opposite sign exists in inventory)
                        // Reductions get their date from matched lot, augmentations get txn date
                        let is_reduction =
                            self.inventories.get(&posting.account).is_some_and(|inv| {
                                inv.positions().iter().any(|pos| {
                                    pos.units.currency == units.currency
                                        && pos.units.number.is_sign_positive()
                                            != units.number.is_sign_positive()
                                })
                            });

                        // Fill in date for augmentations only (not reductions)
                        let inferred_date = if is_reduction {
                            None // Reductions get their date from matched lot
                        } else {
                            cost_spec.date.or(Some(txn.date))
                        };

                        // Only update if we actually inferred something
                        if inferred_currency.is_some() || inferred_date.is_some() {
                            result.postings[idx].cost = Some(CostSpec {
                                number_per: cost_spec.number_per,
                                number_total: cost_spec.number_total,
                                currency: inferred_currency.or_else(|| cost_spec.currency.clone()),
                                date: inferred_date.or(cost_spec.date),
                                label: cost_spec.label.clone(),
                                merge: cost_spec.merge,
                            });
                        }
                    }
                }
            }
        }

        // Apply posting expansions (replace single postings with multiple)
        // Process in reverse order to maintain correct indices
        for (orig_idx, expanded) in expansions.into_iter().rev() {
            result.postings.remove(orig_idx);
            for (i, posting) in expanded.into_iter().enumerate() {
                result.postings.insert(orig_idx + i, posting);
            }
        }

        Ok(BookedTransaction {
            transaction: result,
            gains,
            booked_indices: booked_indices.into_iter().collect(),
        })
    }

    /// Apply a transaction to the inventories (update balances).
    pub fn apply(&mut self, txn: &Transaction) {
        for posting in &txn.postings {
            if let Some(IncompleteAmount::Complete(units)) = &posting.units {
                let inv = self.inventories.entry(posting.account.clone()).or_default();

                // Determine if this is a reduction using is_reduced_by logic:
                // Units reduce inventory when signs differ for the same currency
                let is_reduction = posting.cost.is_some()
                    && inv.positions().iter().any(|pos| {
                        pos.units.currency == units.currency
                            && pos.units.number.is_sign_positive()
                                != units.number.is_sign_positive()
                    });

                if is_reduction {
                    // Reduce from inventory
                    let _ = inv.reduce(units, posting.cost.as_ref(), self.booking_method);
                } else {
                    // Add to inventory
                    let position = if let Some(cost_spec) = &posting.cost {
                        // Try per-unit cost first, then total cost
                        let per_unit_cost = if let Some(per_unit) = &cost_spec.number_per {
                            Some(*per_unit)
                        } else if let Some(total) = &cost_spec.number_total {
                            // Convert total cost to per-unit cost (quantize the calculated value)
                            if units.number.is_zero() {
                                None
                            } else {
                                Some(quantize_calculated(*total / units.number.abs()))
                            }
                        } else {
                            None
                        };

                        // Infer cost currency from price annotation if not specified
                        let cost_currency = cost_spec.currency.clone().or_else(|| {
                            posting.price.as_ref().and_then(|p| match p {
                                rustledger_core::PriceAnnotation::Unit(a)
                                | rustledger_core::PriceAnnotation::Total(a) => {
                                    Some(a.currency.clone())
                                }
                                rustledger_core::PriceAnnotation::UnitIncomplete(inc)
                                | rustledger_core::PriceAnnotation::TotalIncomplete(inc) => {
                                    inc.currency().map(Into::into)
                                }
                                _ => None,
                            })
                        });

                        if let (Some(per_unit), Some(currency)) = (per_unit_cost, cost_currency) {
                            Position::with_cost(
                                units.clone(),
                                Cost::new(per_unit, currency)
                                    .with_date_opt(cost_spec.date.or(Some(txn.date)))
                                    .with_label_opt(cost_spec.label.clone()),
                            )
                        } else {
                            Position::simple(units.clone())
                        }
                    } else {
                        Position::simple(units.clone())
                    };
                    inv.add(position);
                }
            }
        }
    }

    /// Book and interpolate a transaction.
    ///
    /// This fills in empty cost specs, then interpolates any missing amounts.
    pub fn book_and_interpolate(
        &self,
        txn: &Transaction,
    ) -> Result<InterpolationResult, BookingError> {
        // First book (fill in costs)
        let booked = self.book(txn)?;

        // Then interpolate (fill in missing amounts)
        let result = interpolate(&booked.transaction)?;

        Ok(result)
    }
}

/// Book and interpolate a list of transactions.
///
/// This processes transactions in order, tracking inventory to enable
/// proper lot matching and capital gains calculation.
pub fn book_transactions(
    transactions: &[Transaction],
    method: BookingMethod,
) -> Vec<Result<InterpolationResult, BookingError>> {
    let mut engine = BookingEngine::with_method(method);
    let mut results = Vec::with_capacity(transactions.len());

    for txn in transactions {
        let result = engine.book_and_interpolate(txn);
        if let Ok(ref interpolated) = result {
            // Apply the booked transaction (with filled-in costs), not the original
            engine.apply(&interpolated.transaction);
        }
        results.push(result);
    }

    results
}

#[cfg(test)]
mod tests {
    use super::*;
    use rust_decimal_macros::dec;
    use rustledger_core::{NaiveDate, Posting, PriceAnnotation};

    fn date(year: i32, month: u32, day: u32) -> NaiveDate {
        NaiveDate::from_ymd_opt(year, month, day).unwrap()
    }

    #[test]
    fn test_book_simple_buy() {
        let mut engine = BookingEngine::new();

        // Buy 10 AAPL at $150
        let buy = Transaction::new(date(2024, 1, 15), "Buy stock")
            .with_posting(
                Posting::new("Assets:Stock", Amount::new(dec!(10), "AAPL")).with_cost(
                    CostSpec::empty()
                        .with_number_per(dec!(150.00))
                        .with_currency("USD"),
                ),
            )
            .with_posting(Posting::new(
                "Assets:Cash",
                Amount::new(dec!(-1500.00), "USD"),
            ));

        engine.apply(&buy);

        // Check inventory
        let inv = engine.inventory(&"Assets:Stock".into()).unwrap();
        assert_eq!(inv.units("AAPL"), dec!(10));
    }

    #[test]
    fn test_book_sell_with_gain() {
        let mut engine = BookingEngine::new();

        // Buy 10 AAPL at $150
        let buy = Transaction::new(date(2024, 1, 15), "Buy stock")
            .with_posting(
                Posting::new("Assets:Stock", Amount::new(dec!(10), "AAPL")).with_cost(
                    CostSpec::empty()
                        .with_number_per(dec!(150.00))
                        .with_currency("USD"),
                ),
            )
            .with_posting(Posting::new(
                "Assets:Cash",
                Amount::new(dec!(-1500.00), "USD"),
            ));

        engine.apply(&buy);

        // Sell 5 AAPL at $175 with empty cost (needs lot matching)
        let sell = Transaction::new(date(2024, 6, 15), "Sell stock")
            .with_posting(
                Posting::new("Assets:Stock", Amount::new(dec!(-5), "AAPL"))
                    .with_cost(CostSpec::empty()) // Empty - needs lot matching
                    .with_price(PriceAnnotation::Unit(Amount::new(dec!(175.00), "USD"))),
            )
            .with_posting(Posting::new(
                "Assets:Cash",
                Amount::new(dec!(875.00), "USD"),
            ))
            .with_posting(Posting::auto("Income:CapitalGains")); // Elided

        // Check inventory before sell
        let inv = engine.inventory(&"Assets:Stock".into()).unwrap();
        eprintln!("Inventory before sell: {inv:?}");

        let booked = engine.book(&sell).unwrap();
        eprintln!(
            "Booked: gains={:?}, indices={:?}",
            booked.gains, booked.booked_indices
        );
        eprintln!("Booked transaction: {:?}", booked.transaction);

        // Check that gain was calculated
        assert_eq!(
            booked.gains.len(),
            1,
            "Expected 1 gain, got {:?}",
            booked.gains
        );
        let gain = &booked.gains[0];
        // Gain = 5 * (175 - 150) = 125
        assert_eq!(gain.amount.number, dec!(125));
    }

    #[test]
    fn test_book_with_total_cost() {
        let mut engine = BookingEngine::new();

        // Buy 1.763 VIIIX with total cost of 300 USD (like healthequity file)
        let buy = Transaction::new(date(2016, 1, 16), "Buy stock")
            .with_posting(
                Posting::new("Assets:Stock", Amount::new(dec!(1.763), "VIIIX")).with_cost(
                    CostSpec::empty()
                        .with_number_total(dec!(300.00))
                        .with_currency("USD"),
                ),
            )
            .with_posting(Posting::new(
                "Assets:Cash",
                Amount::new(dec!(-300.00), "USD"),
            ));

        engine.apply(&buy);

        // Check inventory
        let inv = engine.inventory(&"Assets:Stock".into()).unwrap();
        eprintln!("Inventory after total cost buy: {inv:?}");
        assert_eq!(inv.units("VIIIX"), dec!(1.763));

        // Check cost was calculated correctly (300/1.763 ≈ 170.16)
        let pos = inv.positions().first().unwrap();
        assert!(pos.cost.is_some(), "Expected cost on position");
        eprintln!("Position cost: {:?}", pos.cost);
    }

    #[test]
    fn test_cost_spec_currency_inference() {
        let mut engine = BookingEngine::new();

        // Create SELLOPT: -1 AAPL {40.0} @ 0.4 USD
        // This has cost number (40.0) but NO cost currency - should infer from price
        let sell = Transaction::new(date(2022, 6, 17), "SELLOPT")
            .with_posting(
                Posting::new("Assets:Stock", Amount::new(dec!(-1), "AAPL"))
                    .with_cost(CostSpec::empty().with_number_per(dec!(40.0)))
                    .with_price(PriceAnnotation::Unit(Amount::new(dec!(0.4), "USD"))),
            )
            .with_posting(Posting::new("Assets:Stock", Amount::new(dec!(40.0), "USD")));

        eprintln!("SELLOPT posting.cost = {:?}", sell.postings[0].cost);
        eprintln!("SELLOPT posting.price = {:?}", sell.postings[0].price);

        engine.apply(&sell);

        let inv = engine.inventory(&"Assets:Stock".into()).unwrap();
        eprintln!("Inventory after SELLOPT: {inv:?}");

        // Check that the AAPL position has cost with USD currency
        let aapl_pos = inv
            .positions()
            .iter()
            .find(|p| p.units.currency.as_ref() == "AAPL")
            .expect("Should have AAPL position");

        eprintln!("AAPL position: {aapl_pos:?}");

        assert!(aapl_pos.cost.is_some(), "AAPL position should have cost");
        let cost = aapl_pos.cost.as_ref().unwrap();
        assert_eq!(cost.currency.as_ref(), "USD", "Cost currency should be USD");
        assert_eq!(cost.number, dec!(40.0), "Cost number should be 40.0");
    }

    #[test]
    fn test_booking_engine_with_method() {
        // Test that with_method creates engine with specified booking method
        let engine = BookingEngine::with_method(BookingMethod::Lifo);
        assert!(engine.inventories.is_empty());

        // Also test default is FIFO
        let default_engine = BookingEngine::new();
        assert!(default_engine.inventories.is_empty());
    }

    #[test]
    fn test_book_sell_with_total_price() {
        let mut engine = BookingEngine::new();

        // Buy 10 AAPL at $150
        let buy = Transaction::new(date(2024, 1, 15), "Buy stock")
            .with_posting(
                Posting::new("Assets:Stock", Amount::new(dec!(10), "AAPL")).with_cost(
                    CostSpec::empty()
                        .with_number_per(dec!(150.00))
                        .with_currency("USD"),
                ),
            )
            .with_posting(Posting::new(
                "Assets:Cash",
                Amount::new(dec!(-1500.00), "USD"),
            ));

        engine.apply(&buy);

        // Sell 5 AAPL with total price annotation (not per-unit)
        // Total price = $875 for 5 shares = $175/share
        let sell = Transaction::new(date(2024, 6, 15), "Sell stock")
            .with_posting(
                Posting::new("Assets:Stock", Amount::new(dec!(-5), "AAPL"))
                    .with_cost(CostSpec::empty())
                    .with_price(PriceAnnotation::Total(Amount::new(dec!(875.00), "USD"))),
            )
            .with_posting(Posting::new(
                "Assets:Cash",
                Amount::new(dec!(875.00), "USD"),
            ))
            .with_posting(Posting::auto("Income:CapitalGains"));

        let booked = engine.book(&sell).unwrap();

        // Check that gain was calculated correctly
        // Gain = 875 - (5 * 150) = 875 - 750 = 125
        assert_eq!(booked.gains.len(), 1, "Expected 1 gain");
        let gain = &booked.gains[0];
        assert_eq!(gain.amount.number, dec!(125));
    }

    #[test]
    fn test_book_transactions_multiple() {
        // Buy 10 AAPL at $150
        let buy = Transaction::new(date(2024, 1, 15), "Buy stock")
            .with_posting(
                Posting::new("Assets:Stock", Amount::new(dec!(10), "AAPL")).with_cost(
                    CostSpec::empty()
                        .with_number_per(dec!(150.00))
                        .with_currency("USD"),
                ),
            )
            .with_posting(Posting::new(
                "Assets:Cash",
                Amount::new(dec!(-1500.00), "USD"),
            ));

        // Sell 5 AAPL
        let sell = Transaction::new(date(2024, 6, 15), "Sell stock")
            .with_posting(
                Posting::new("Assets:Stock", Amount::new(dec!(-5), "AAPL"))
                    .with_cost(CostSpec::empty())
                    .with_price(PriceAnnotation::Unit(Amount::new(dec!(175.00), "USD"))),
            )
            .with_posting(Posting::new(
                "Assets:Cash",
                Amount::new(dec!(875.00), "USD"),
            ))
            .with_posting(Posting::auto("Income:CapitalGains"));

        let transactions = vec![buy, sell];
        let results = book_transactions(&transactions, BookingMethod::Fifo);

        assert_eq!(results.len(), 2);
        assert!(results[0].is_ok());
        assert!(results[1].is_ok());
    }

    #[test]
    fn test_book_augmentation_not_reduction() {
        let mut engine = BookingEngine::new();

        // First, add existing inventory with positive AAPL
        let buy = Transaction::new(date(2024, 1, 15), "Buy stock")
            .with_posting(
                Posting::new("Assets:Stock", Amount::new(dec!(10), "AAPL")).with_cost(
                    CostSpec::empty()
                        .with_number_per(dec!(150.00))
                        .with_currency("USD"),
                ),
            )
            .with_posting(Posting::new(
                "Assets:Cash",
                Amount::new(dec!(-1500.00), "USD"),
            ));

        engine.apply(&buy);

        // Now try to book another buy (augmentation, not reduction)
        // This has empty cost but same sign as inventory, so it's not a reduction
        let another_buy = Transaction::new(date(2024, 2, 15), "Buy more")
            .with_posting(
                Posting::new("Assets:Stock", Amount::new(dec!(5), "AAPL"))
                    .with_cost(CostSpec::empty()), // Empty cost but augmentation
            )
            .with_posting(Posting::new(
                "Assets:Cash",
                Amount::new(dec!(-750.00), "USD"),
            ));

        // Should not error - just skip lot matching for augmentation
        let booked = engine.book(&another_buy).unwrap();
        assert!(
            booked.booked_indices.is_empty(),
            "Augmentation should not have booked indices"
        );
    }

    #[test]
    fn test_book_no_inventory_for_account() {
        let engine = BookingEngine::new();

        // Try to book a sell without any prior inventory
        let sell = Transaction::new(date(2024, 6, 15), "Sell stock")
            .with_posting(
                Posting::new("Assets:Stock", Amount::new(dec!(-5), "AAPL"))
                    .with_cost(CostSpec::empty()),
            )
            .with_posting(Posting::new(
                "Assets:Cash",
                Amount::new(dec!(875.00), "USD"),
            ));

        // Should succeed but with no booked indices (no inventory to match against)
        let booked = engine.book(&sell).unwrap();
        assert!(
            booked.booked_indices.is_empty(),
            "No inventory means no lot matching"
        );
    }

    #[test]
    fn test_book_zero_gain() {
        let mut engine = BookingEngine::new();

        // Buy 10 AAPL at $150
        let buy = Transaction::new(date(2024, 1, 15), "Buy stock")
            .with_posting(
                Posting::new("Assets:Stock", Amount::new(dec!(10), "AAPL")).with_cost(
                    CostSpec::empty()
                        .with_number_per(dec!(150.00))
                        .with_currency("USD"),
                ),
            )
            .with_posting(Posting::new(
                "Assets:Cash",
                Amount::new(dec!(-1500.00), "USD"),
            ));

        engine.apply(&buy);

        // Sell at same price - zero gain
        let sell = Transaction::new(date(2024, 6, 15), "Sell stock")
            .with_posting(
                Posting::new("Assets:Stock", Amount::new(dec!(-5), "AAPL"))
                    .with_cost(CostSpec::empty())
                    .with_price(PriceAnnotation::Unit(Amount::new(dec!(150.00), "USD"))),
            )
            .with_posting(Posting::new(
                "Assets:Cash",
                Amount::new(dec!(750.00), "USD"),
            ));

        let booked = engine.book(&sell).unwrap();

        // Zero gain should not be added to gains vector
        assert!(booked.gains.is_empty(), "Zero gain should not be recorded");
    }
}
