#!/usr/bin/env bash
# Regenerate the TypeScript bindings for `rustledger-wasm`.
#
# Runs `cargo test` with the `ts-export` feature, which triggers
# ts-rs's per-type `.d.ts` emission, then concatenates the per-type
# files into a single `bindings/index.d.ts` that is the canonical
# public TS API surface (ADR-0004 Phase 1).
#
# Two post-process steps over the raw ts-rs output:
#
# 1. **Concatenate + dedupe**. Each per-type file has a `// This file
#    was generated by [ts-rs]...` header and per-file `import type`
#    statements. The concatenated bundle needs neither -- types
#    reference each other within the same file.
#
# 2. **Override `TypedValueJson` with the narrowed discriminated
#    union.** ts-rs emits the wide struct shape
#    `{ type: ...union, value: MetaValueJson }`; the hand-tuned
#    discriminated union from #1215 narrows `value`'s shape per
#    `type` variant. The Rust DTO can't express this structurally
#    (it would need a tagged enum with a custom Deserialize for the
#    `null` variant), so the override lives here.
#
# CI runs this script via `--check` mode (set `RUSTLEDGER_TS_CHECK=1`)
# which fails if the regenerated `bindings/index.d.ts` differs from
# the checked-in version. Local contributors run it without the env
# var to regenerate and commit.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
WASM_DIR="$REPO_ROOT/crates/rustledger-wasm"
RAW_DIR="$WASM_DIR/bindings/bindings"
OUTPUT="$WASM_DIR/bindings/index.d.ts"

# Run the export. `cargo test --features ts-export` triggers ts-rs's
# auto-generated `export_bindings_<type>` test functions, which write
# the per-type .d.ts files. `--quiet` keeps the test summary terse;
# failures still surface via the exit code (set -e at the top).
echo "Generating per-type bindings..." >&2
(cd "$REPO_ROOT" && cargo test -p rustledger-wasm --features ts-export --lib --quiet)

if [ ! -d "$RAW_DIR" ]; then
    echo "error: expected ts-rs output at $RAW_DIR" >&2
    exit 1
fi

# Sort the per-type files for a deterministic output order so the
# generated file's diff stays stable across regen runs. Force the C
# locale so `Ledger.ts` and `LedgerOptions.ts` (and similar pairs
# where punctuation interacts with letters) sort identically on every
# machine. en_US.UTF-8 and C disagree on the relative order of `.`
# (0x2E) vs uppercase letters in some glibc versions -- which broke
# CI's freshness gate before this was pinned.
mapfile -t TS_FILES < <(find "$RAW_DIR" -name '*.ts' | LC_ALL=C sort)

if [ "${#TS_FILES[@]}" -eq 0 ]; then
    echo "error: no .ts files found under $RAW_DIR" >&2
    exit 1
fi

TMP_OUT="$(mktemp)"
trap 'rm -f "$TMP_OUT"' EXIT

# Header.
cat > "$TMP_OUT" << 'EOF'
// AUTO-GENERATED -- DO NOT EDIT.
//
// This file is regenerated by `scripts/regen-ts-bindings.sh` from the
// Rust DTOs in `crates/rustledger-wasm/src/types.rs`. Run the script
// after changing any DTO; CI fails if this file drifts from the
// generator output. See ADR-0004 (#1218) for the design.

EOF

# Concatenate every per-type file, stripping the per-file generated-by
# header line and any `import type` statements (all types resolve
# within this single file). Skip TypedValueJson -- it gets replaced
# with the hand-tuned discriminated union below.
for f in "${TS_FILES[@]}"; do
    name="$(basename "$f" .ts)"
    if [ "$name" = "TypedValueJson" ]; then
        continue
    fi
    sed -e '/^\/\/ This file was generated by \[ts-rs\]/d' \
        -e '/^import type/d' "$f" >> "$TMP_OUT"
    echo "" >> "$TMP_OUT"
done

# Hand-tuned override for `TypedValueJson` -- ADR-0004 #4.
#
# ts-rs emits `{ type: "string" | "amount" | ..., value: MetaValueJson }`
# which doesn't narrow `value` when discriminating on `type`. The
# narrowed shape below pairs each `type` literal with the right
# payload type so `switch (v.type) { case "amount": v.value.number ... }`
# narrows correctly.
#
# When a new MetaValue variant is added on the Rust side, both the
# `meta_value_to_typed_json` converter AND this override need updating.
# The narrowing is hand-tuned because the Rust DTO is a struct
# (`{value_type, value}`), not a tagged enum -- restructuring as an
# enum is awkward because the `null` variant's payload doesn't have
# a clean serde representation. See ADR-0004 for the design rationale.
cat >> "$TMP_OUT" << 'EOF'

/**
 * Tagged-union value used in `DirectiveJson::Custom`'s `values` field
 * (issue #1207). Narrowed discriminated union -- `switch (v.type)` (or
 * `if (v.type === "amount")`) narrows `v.value` to the right payload
 * shape.
 *
 * **Hand-tuned override** of the auto-generated `TypedValueJson` -- the
 * Rust DTO is a struct, not a tagged enum, so ts-rs can't emit the
 * narrowing on its own. See ADR-0004 (#1218).
 */
export type TypedValueJson =
    | { type: "string"; value: string }
    | { type: "account"; value: string }
    | { type: "currency"; value: string }
    | { type: "tag"; value: string }
    | { type: "link"; value: string }
    | { type: "date"; value: string }
    | { type: "number"; value: string }
    | { type: "bool"; value: boolean }
    | { type: "amount"; value: { number: string; currency: string } }
    | { type: "null"; value: null };
EOF

# Format hint: collapse 3+ consecutive blank lines into 2. Cosmetic
# only; keeps the bundle readable when several short types are
# concatenated.
awk 'BEGIN { blank = 0 }
     /^$/ { blank++; if (blank <= 2) print; next }
     { blank = 0; print }' "$TMP_OUT" > "$OUTPUT.new"

# Run the bundle through Prettier (#1226). ts-rs emits a compact
# one-line-per-field layout that wasm-bindgen's typescript_custom_section
# formatter miscounts brackets on -- the result is escalating
# indentation in the generated `pkg/*.d.ts`. Prettier normalizes the
# layout (proper indentation, semicolons, line breaks) so wasm-bindgen
# embeds clean output. As a side effect, the checked-in
# `bindings/index.d.ts` is easier to read and review.
#
# `npx --yes` accepts the prompt to download `prettier` if not cached.
# Both `npx` and `prettier` are available in CI via the existing Node
# toolchain that wasm-pack uses.
if ! command -v npx >/dev/null 2>&1; then
    echo "error: npx not found in PATH. Install Node.js to regenerate." >&2
    exit 1
fi
npx --yes prettier@3 --parser=typescript --no-semi=false --print-width=100 \
    < "$OUTPUT.new" > "$OUTPUT.fmt" 2> "$OUTPUT.err" || {
    echo "error: prettier failed to format the bundle:" >&2
    cat "$OUTPUT.err" >&2
    rm -f "$OUTPUT.new" "$OUTPUT.fmt" "$OUTPUT.err"
    exit 1
}
rm -f "$OUTPUT.new" "$OUTPUT.err"
mv "$OUTPUT.fmt" "$OUTPUT"

# CI-only mode: fail if the regenerated file differs from the
# committed one. Local contributors run without this env var.
if [ "${RUSTLEDGER_TS_CHECK:-}" = "1" ]; then
    if ! git diff --exit-code -- "$OUTPUT" >/dev/null 2>&1; then
        echo "error: $OUTPUT differs from the committed version." >&2
        echo "Did you modify a wire-format DTO without running" >&2
        echo "scripts/regen-ts-bindings.sh? Diff:" >&2
        git --no-pager diff -- "$OUTPUT" >&2
        exit 1
    fi
    echo "OK: TS bindings match the committed state." >&2
else
    echo "Regenerated: $OUTPUT" >&2
fi
